export type OpenApiSchema = Record<string, unknown>;

const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });

export const aixOpenApiComponents: Record<string, OpenApiSchema> = {
  CredentialSummary: {
    type: "object",
    required: ["id", "entityId", "label", "preset", "createdAt", "lastUsedAt", "expiresAt", "revokedAt"],
    properties: {
      id: { type: "string" },
      entityId: { type: "string" },
      label: { type: ["string", "null"] },
      preset: { type: "string", enum: ["offboarding", "ongoing"] },
      createdAt: { type: "number" },
      lastUsedAt: { type: ["number", "null"] },
      expiresAt: { type: ["number", "null"] },
      revokedAt: { type: ["number", "null"] },
    },
  },
  SetupBundle: {
    type: "object",
    required: ["runtimeBaseUrl", "token", "commands", "promptText"],
    properties: {
      runtimeBaseUrl: { type: "string", format: "uri" },
      token: { type: "string" },
      commands: { type: "array", items: { type: "string" } },
      promptText: { type: "string" },
    },
  },
  EntitySummary: {
    type: "object",
    required: ["id", "name", "type", "normalized", "isUser", "isAgent", "origin", "createdAt"],
    properties: {
      id: { type: "string" },
      name: { type: "string" },
      type: { type: ["string", "null"] },
      normalized: { type: ["string", "null"] },
      isUser: { type: "boolean" },
      isAgent: { type: "boolean" },
      origin: { type: ["string", "null"] },
      createdAt: { type: ["number", "null"] },
    },
  },
  SourceProviderSummary: {
    type: "object",
    required: ["provider", "enabled", "lastSeenAt"],
    properties: {
      provider: { type: "string" },
      enabled: { type: "boolean" },
      lastSeenAt: { type: "number" },
    },
  },
  SourceProviderDetail: {
    type: "object",
    required: ["provider", "enabled", "firstSeenAt", "lastSeenAt"],
    properties: {
      provider: { type: "string" },
      enabled: { type: "boolean" },
      firstSeenAt: { type: "number" },
      lastSeenAt: { type: "number" },
    },
  },
  SourceHealth: {
    type: "string",
    enum: ["healthy", "stale", "failed", "idle"],
  },
  SourceSummary: {
    type: "object",
    required: [
      "id",
      "entityId",
      "installId",
      "currentDeviceId",
      "label",
      "status",
      "defaultMode",
      "expectedCadence",
      "lastSeenAt",
      "lastSuccessAt",
      "lastFailureAt",
      "lastRunId",
      "lastError",
      "clientVersion",
      "providers",
      "health",
    ],
    properties: {
      id: { type: "string" },
      entityId: { type: "string" },
      installId: { type: "string" },
      currentDeviceId: { type: ["string", "null"] },
      label: { type: ["string", "null"] },
      status: { type: "string", enum: ["active", "paused", "revoked", "error"] },
      defaultMode: { type: "string", enum: ["backfill", "incremental", "live"] },
      expectedCadence: { type: "string", enum: ["manual", "five_minutes", "ten_minutes", "daily", "live"] },
      lastSeenAt: { type: "number" },
      lastSuccessAt: { type: ["number", "null"] },
      lastFailureAt: { type: ["number", "null"] },
      lastRunId: { type: ["string", "null"] },
      lastError: { type: ["string", "null"] },
      clientVersion: { type: ["string", "null"] },
      providers: { type: "array", items: ref("SourceProviderSummary") },
      health: ref("SourceHealth"),
    },
  },
  SourceDetail: {
    type: "object",
    required: [
      "id",
      "entityId",
      "installId",
      "currentDeviceId",
      "label",
      "status",
      "defaultMode",
      "expectedCadence",
      "firstSeenAt",
      "lastSeenAt",
      "lastSuccessAt",
      "lastFailureAt",
      "lastRunId",
      "lastError",
      "clientVersion",
      "metadata",
    ],
    properties: {
      id: { type: "string" },
      entityId: { type: "string" },
      installId: { type: "string" },
      currentDeviceId: { type: ["string", "null"] },
      label: { type: ["string", "null"] },
      status: { type: "string", enum: ["active", "paused", "revoked", "error"] },
      defaultMode: { type: "string", enum: ["backfill", "incremental", "live"] },
      expectedCadence: { type: "string", enum: ["manual", "five_minutes", "ten_minutes", "daily", "live"] },
      firstSeenAt: { type: "number" },
      lastSeenAt: { type: "number" },
      lastSuccessAt: { type: ["number", "null"] },
      lastFailureAt: { type: ["number", "null"] },
      lastRunId: { type: ["string", "null"] },
      lastError: { type: ["string", "null"] },
      clientVersion: { type: ["string", "null"] },
      metadata: { type: ["object", "null"], additionalProperties: true },
    },
  },
  DeviceSummary: {
    type: "object",
    required: ["id", "clientDeviceId", "hostname", "platform", "arch", "osVersion", "lastSeenAt"],
    properties: {
      id: { type: "string" },
      clientDeviceId: { type: "string" },
      hostname: { type: ["string", "null"] },
      platform: { type: ["string", "null"] },
      arch: { type: ["string", "null"] },
      osVersion: { type: ["string", "null"] },
      lastSeenAt: { type: ["number", "null"] },
    },
  },
  RunStartSummary: {
    type: "object",
    required: ["id", "sourceId", "entityId", "clientRunId", "status", "startedAt"],
    properties: {
      id: { type: "string" },
      sourceId: { type: "string" },
      entityId: { type: "string" },
      clientRunId: { type: "string" },
      status: { type: "string", enum: ["running", "completed", "completed_empty", "failed", "partial"] },
      startedAt: { type: "number" },
    },
  },
  RunSummary: {
    type: "object",
    required: [
      "id",
      "sourceId",
      "entityId",
      "clientRunId",
      "triggerKind",
      "runMode",
      "status",
      "startedAt",
      "completedAt",
      "sessionsSeen",
      "sessionsChanged",
      "imported",
      "upserted",
      "skipped",
      "failed",
      "bytesUploaded",
      "uploadCount",
      "errorCode",
      "errorMessage",
    ],
    properties: {
      id: { type: "string" },
      sourceId: { type: "string" },
      entityId: { type: "string" },
      clientRunId: { type: "string" },
      triggerKind: { type: "string", enum: ["manual", "scheduled", "live", "resume"] },
      runMode: { type: "string", enum: ["backfill", "incremental", "live"] },
      status: { type: "string", enum: ["running", "completed", "completed_empty", "failed", "partial"] },
      startedAt: { type: "number" },
      completedAt: { type: ["number", "null"] },
      sessionsSeen: { type: "number" },
      sessionsChanged: { type: "number" },
      imported: { type: "number" },
      upserted: { type: "number" },
      skipped: { type: "number" },
      failed: { type: "number" },
      bytesUploaded: { type: "number" },
      uploadCount: { type: "number" },
      errorCode: { type: ["string", "null"] },
      errorMessage: { type: ["string", "null"] },
    },
  },
  UploadRange: {
    type: "object",
    required: ["start", "end"],
    properties: {
      start: { type: "number" },
      end: { type: "number" },
    },
  },
  UploadRecord: {
    type: "object",
    required: [
      "id",
      "runId",
      "sourceId",
      "status",
      "contentKind",
      "payloadSha256",
      "chunkTotal",
      "receivedRanges",
      "bytesReceived",
      "itemCount",
      "createdAt",
      "updatedAt",
      "completedAt",
      "errorCode",
      "errorMessage",
      "result",
    ],
    properties: {
      id: { type: "string" },
      runId: { type: "string" },
      sourceId: { type: "string" },
      status: { type: "string", enum: ["staging", "completed", "failed"] },
      contentKind: { type: "string" },
      payloadSha256: { type: "string" },
      chunkTotal: { type: "number" },
      receivedRanges: { type: "array", items: ref("UploadRange") },
      bytesReceived: { type: "number" },
      itemCount: { type: "number" },
      createdAt: { type: "number" },
      updatedAt: { type: "number" },
      completedAt: { type: ["number", "null"] },
      errorCode: { type: ["string", "null"] },
      errorMessage: { type: ["string", "null"] },
      result: { type: ["object", "null"], additionalProperties: true },
    },
  },
  RunDetail: {
    allOf: [
      ref("RunSummary"),
      {
        type: "object",
        required: ["checkpoint"],
        properties: {
          checkpoint: { type: ["object", "null"], additionalProperties: true },
        },
      },
    ],
  },
  ImportStats: {
    type: "object",
    required: ["imported", "upserted", "skipped", "failed"],
    properties: {
      imported: { type: "number" },
      upserted: { type: "number" },
      skipped: { type: "number" },
      failed: { type: "number" },
    },
  },
  UploadSummary: {
    type: "object",
    required: ["id", "status", "chunkTotal", "receivedRanges", "bytesReceived"],
    properties: {
      id: { type: "string" },
      status: { type: "string" },
      chunkTotal: { type: "number" },
      receivedRanges: { type: "array", items: ref("UploadRange") },
      bytesReceived: { type: "number" },
    },
  },
  ImportedSession: {
    type: "object",
    required: [
      "sessionKey",
      "sourceEntityId",
      "aixSourceId",
      "sourceProvider",
      "sourceSessionId",
      "updatedAt",
      "title",
      "workspaceId",
    ],
    properties: {
      sessionKey: { type: "string" },
      sourceEntityId: { type: "string" },
      aixSourceId: { type: "string" },
      sourceProvider: { type: "string" },
      sourceSessionId: { type: "string" },
      updatedAt: { type: "number" },
      title: { type: ["string", "null"] },
      workspaceId: { type: ["string", "null"] },
    },
  },
};

export const aixResponseSchemasByMethod: Record<string, OpenApiSchema> = {
  "aix.credentials.issue": {
    type: "object",
    required: ["ok", "credential", "token", "setupBundle"],
    properties: {
      ok: { type: "boolean", enum: [true] },
      credential: ref("CredentialSummary"),
      token: { type: "string" },
      setupBundle: ref("SetupBundle"),
    },
  },
  "aix.credentials.list": {
    type: "object",
    required: ["credentials"],
    properties: {
      credentials: { type: "array", items: ref("CredentialSummary") },
    },
  },
  "aix.credentials.revoke": {
    type: "object",
    required: ["ok", "revoked"],
    properties: {
      ok: { type: "boolean", enum: [true] },
      revoked: { type: "boolean" },
    },
  },
  "aix.credentials.rotate": {
    type: "object",
    required: ["ok", "previousId", "credential", "token", "setupBundle"],
    properties: {
      ok: { type: "boolean", enum: [true] },
      previousId: { type: "string" },
      credential: ref("CredentialSummary"),
      token: { type: "string" },
      setupBundle: ref("SetupBundle"),
    },
  },
  "aix.entities.list": {
    type: "object",
    required: ["entities"],
    properties: {
      entities: { type: "array", items: ref("EntitySummary") },
    },
  },
  "aix.sources.register": {
    type: "object",
    required: ["ok", "source", "runtime"],
    properties: {
      ok: { type: "boolean", enum: [true] },
      source: {
        type: "object",
        required: ["id", "entityId", "installId", "currentDeviceId", "status", "defaultMode", "expectedCadence"],
        properties: {
          id: { type: "string" },
          entityId: { type: "string" },
          installId: { type: "string" },
          currentDeviceId: { type: ["string", "null"] },
          status: { type: "string", enum: ["active", "paused", "revoked", "error"] },
          defaultMode: { type: "string", enum: ["backfill", "incremental", "live"] },
          expectedCadence: { type: "string", enum: ["manual", "five_minutes", "ten_minutes", "daily", "live"] },
        },
      },
      runtime: {
        type: "object",
        required: ["baseUrl", "operationsPath"],
        properties: {
          baseUrl: { type: "string", format: "uri" },
          operationsPath: { type: "string" },
        },
      },
    },
  },
  "aix.sources.list": {
    type: "object",
    required: ["sources"],
    properties: {
      sources: { type: "array", items: ref("SourceSummary") },
    },
  },
  "aix.sources.get": {
    type: "object",
    required: ["source", "device", "providers"],
    properties: {
      source: ref("SourceDetail"),
      device: {
        anyOf: [ref("DeviceSummary"), { type: "null" }],
      },
      providers: { type: "array", items: ref("SourceProviderDetail") },
    },
  },
  "aix.sources.update": {
    type: "object",
    required: ["ok", "sourceId"],
    properties: {
      ok: { type: "boolean", enum: [true] },
      sourceId: { type: "string" },
    },
  },
  "aix.runs.begin": {
    type: "object",
    required: ["ok", "run", "existing"],
    properties: {
      ok: { type: "boolean", enum: [true] },
      run: ref("RunStartSummary"),
      existing: { type: "boolean" },
    },
  },
  "aix.runs.complete": {
    type: "object",
    required: ["ok", "runId"],
    properties: {
      ok: { type: "boolean", enum: [true] },
      runId: { type: "string" },
    },
  },
  "aix.runs.list": {
    type: "object",
    required: ["runs"],
    properties: {
      runs: { type: "array", items: ref("RunSummary") },
    },
  },
  "aix.runs.get": {
    type: "object",
    required: ["run", "uploads"],
    properties: {
      run: ref("RunDetail"),
      uploads: { type: "array", items: ref("UploadRecord") },
    },
  },
  "aix.uploads.begin": {
    type: "object",
    required: ["ok", "upload"],
    properties: {
      ok: { type: "boolean", enum: [true] },
      upload: ref("UploadSummary"),
    },
  },
  "aix.uploads.chunk": {
    type: "object",
    required: ["ok", "uploadId", "status", "receivedRanges", "bytesReceived"],
    properties: {
      ok: { type: "boolean", enum: [true] },
      uploadId: { type: "string" },
      status: { type: "string", enum: ["staging", "completed", "failed"] },
      receivedRanges: { type: "array", items: ref("UploadRange") },
      bytesReceived: { type: "number" },
    },
  },
  "aix.uploads.status": {
    type: "object",
    required: ["ok", "uploadId", "status", "chunkTotal", "receivedRanges", "bytesReceived"],
    properties: {
      ok: { type: "boolean", enum: [true] },
      uploadId: { type: "string" },
      status: { type: "string", enum: ["missing", "staging", "completed", "failed"] },
      chunkTotal: { anyOf: [{ type: "number" }, { type: "null" }] },
      receivedRanges: { type: "array", items: ref("UploadRange") },
      bytesReceived: { type: "number" },
      result: ref("ImportStats"),
    },
  },
  "aix.uploads.complete": {
    type: "object",
    required: ["ok", "uploadId", "status", "import"],
    properties: {
      ok: { type: "boolean", enum: [true] },
      uploadId: { type: "string" },
      status: { type: "string", enum: ["completed"] },
      import: ref("ImportStats"),
    },
  },
  "aix.imported-sessions.list": {
    type: "object",
    required: ["items"],
    properties: {
      items: { type: "array", items: ref("ImportedSession") },
      nextCursor: { type: "string" },
    },
  },
};
