#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export GITHUB_SETUP_REPOSITORY_SELECTION="${GITHUB_SETUP_REPOSITORY_SELECTION:-all}"
export GITHUB_INITIAL_BACKFILL_SINCE="${GITHUB_INITIAL_BACKFILL_SINCE:-2025-01-01T00:00:00Z}"
export FORGE_BACKFILL_WAIT_TIMEOUT_MS="${FORGE_BACKFILL_WAIT_TIMEOUT_MS:-5400000}"
export FORGE_BACKFILL_WAIT_POLL_MS="${FORGE_BACKFILL_WAIT_POLL_MS:-5000}"
export FORGE_ENABLE_INGEST_PROOF="${FORGE_ENABLE_INGEST_PROOF:-1}"

exec "$SCRIPT_DIR/github-live-cleanroom-docker.sh"
