"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type {
  GlowbotAgentsRecommendationsResponse,
  GlowbotModelingResponse,
  GlowbotOverviewResponse,
} from "@/lib/glowbot";
import { GLOWBOT_METHODS } from "@/lib/glowbot";
import { rpcCall } from "@/lib/nex-client";

function StarIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#c9a84c" strokeWidth="1.5">
      <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
    </svg>
  );
}

function ArrowUpRightIcon() {
  return (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M7 17L17 7M17 7H7M17 7V17" />
    </svg>
  );
}

function MiniBarChart() {
  const bars = [65, 70, 55, 75, 60, 80, 72, 85, 78, 90];
  return (
    <div className="flex items-end gap-1.5 h-10 mt-4">
      {bars.map((h, i) => (
        <div
          key={i}
          className="flex-1 rounded-sm bg-gb-gold-dim/60"
          style={{ height: `${h}%` }}
        />
      ))}
    </div>
  );
}

type OverviewState = {
  overview: GlowbotOverviewResponse;
  recommendationDetails: GlowbotAgentsRecommendationsResponse;
  spendToConsultsModel: GlowbotModelingResponse;
  reviewVelocityModel: GlowbotModelingResponse;
  noShowModel: GlowbotModelingResponse;
};

export default function OverviewPage() {
  const [state, setState] = useState<OverviewState | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    const run = async () => {
      try {
        const [overview, recommendationDetails, spendToConsultsModel, reviewVelocityModel, noShowModel] =
          await Promise.all([
            rpcCall<GlowbotOverviewResponse>(GLOWBOT_METHODS.overview, { period: "30d" }),
            rpcCall<GlowbotAgentsRecommendationsResponse>(GLOWBOT_METHODS.agentsRecommendations, {
              limit: 4,
            }),
            rpcCall<GlowbotModelingResponse>(GLOWBOT_METHODS.modeling, {
              model: "ad_spend_to_consults",
              window: "6m",
            }),
            rpcCall<GlowbotModelingResponse>(GLOWBOT_METHODS.modeling, {
              model: "review_velocity",
              window: "6m",
            }),
            rpcCall<GlowbotModelingResponse>(GLOWBOT_METHODS.modeling, {
              model: "noshow_rate",
              window: "6m",
            }),
          ]);
        if (!cancelled) {
          setState({
            overview,
            recommendationDetails,
            spendToConsultsModel,
            reviewVelocityModel,
            noShowModel,
          });
          setError(null);
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : String(err));
        }
      }
    };
    void run();
    return () => {
      cancelled = true;
    };
  }, []);

  const view = useMemo(() => {
    if (!state) {
      return null;
    }
    const { overview, recommendationDetails, spendToConsultsModel, reviewVelocityModel, noShowModel } = state;
    const actionDetailsByTitle = new Map(
      recommendationDetails.recommendations.map((item) => [item.title, item.description]),
    );
    const actions = overview.topActions.map((item) => ({
      title: item.title,
      delta: `+${item.deltaValue}`,
      unit: item.deltaUnit,
      desc: actionDetailsByTitle.get(item.title) ?? "Recommendation generated by GlowBot analysis.",
      confidence: item.confidence,
    }));
    const drivers = [
      {
        title: "Ad Spend",
        arrow: "Booked Consults",
        rows: [
          { label: "Model", value: "ad_spend_to_consults", gold: false },
          { label: "Trend", value: spendToConsultsModel.summary.trend, gold: true },
        ],
      },
      {
        title: "Review Velocity",
        arrow: "Call Volume",
        rows: [
          { label: "Model", value: "review_velocity", gold: false },
          { label: "Trend", value: reviewVelocityModel.summary.trend, gold: true },
        ],
      },
      {
        title: "No-Show Rate",
        arrow: "Lost Patients",
        rows: [
          { label: "Model", value: "noshow_rate", gold: false },
          { label: "Trend", value: noShowModel.summary.trend, gold: true },
        ],
      },
    ];
    const deltaPrefix = overview.heroStat.delta > 0 ? "+" : "";
    const deltaPercentPrefix = overview.heroStat.deltaPercent > 0 ? "+" : "";
    return {
      overview,
      actions,
      drivers,
      deltaPrefix,
      deltaPercentPrefix,
    };
  }, [state]);

  return (
    <div className="space-y-16">
      {error && (
        <section className="bg-gb-card border border-gb-gold rounded-lg p-4 text-sm text-gb-muted">
          Failed to load overview: {error}
        </section>
      )}

      {!state && !error && (
        <section className="bg-gb-card border border-gb-border rounded-lg p-4 text-sm text-gb-muted">
          Loading overview...
        </section>
      )}

      {view && (
        <>
          <section className="text-center space-y-3">
            <h1 className="text-[120px] leading-none font-[family-name:var(--font-serif)] text-gb-gold">
              {view.overview.heroStat.value}
            </h1>
            <p className="text-lg font-semibold">{view.overview.heroStat.label}</p>
            <div className="flex items-center justify-center gap-2 text-gb-gold">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M2 16c3-6 5-2 8-8s5 2 8-4" />
              </svg>
              <span className="text-sm">
                {view.deltaPrefix}
                {view.overview.heroStat.delta} (
                {view.deltaPercentPrefix}
                {view.overview.heroStat.deltaPercent}%) {view.overview.heroStat.comparedTo}
              </span>
            </div>
            <div className="flex justify-center pt-2">
              <svg width="180" height="30" viewBox="0 0 180 30">
                <path
                  d="M0 25 C20 22, 40 15, 60 18 S100 8, 120 12 S160 5, 180 8"
                  fill="none"
                  stroke="#c9a84c"
                  strokeWidth="2"
                  strokeLinecap="round"
                  className="sparkline-animate"
                />
              </svg>
            </div>
          </section>

          <section className="space-y-6">
            <div className="text-center space-y-2">
              <h2 className="text-3xl font-[family-name:var(--font-serif)]">Top Growth Actions</h2>
              <p className="text-gb-muted text-sm">Prioritized by impact and confidence</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {view.actions.map((a) => (
                <div
                  key={a.title}
                  className="bg-gb-card border border-gb-gold/60 rounded-lg p-6 flex flex-col justify-between"
                >
                  <div>
                    <div className="flex items-start justify-between mb-4">
                      <h3 className="text-gb-gold text-lg">{a.title}</h3>
                      <StarIcon />
                    </div>
                    <p className="text-4xl font-[family-name:var(--font-serif)] text-gb-gold mb-1">
                      {a.delta}
                    </p>
                    <p className="text-sm font-semibold mb-4">{a.unit}</p>
                    <p className="text-gb-muted text-sm leading-relaxed">{a.desc}</p>
                  </div>
                  <div className="mt-6 pt-4 border-t border-gb-border flex items-center justify-between">
                    <span className="text-xs font-semibold tracking-widest">
                      {a.confidence} CONFIDENCE
                    </span>
                    <ArrowUpRightIcon />
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-3xl font-[family-name:var(--font-serif)] text-center">
              What Drives Bookings
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {view.drivers.map((d) => (
                <div key={d.title} className="bg-gb-card border border-gb-border rounded-lg p-6">
                  <h3 className="font-semibold mb-4">
                    {d.title} <span className="text-gb-muted mx-1">&rarr;</span> {d.arrow}
                  </h3>
                  <div className="space-y-3">
                    {d.rows.map((r) => (
                      <div key={r.label} className="flex justify-between text-sm">
                        <span className="text-gb-muted">{r.label}</span>
                        <span className={r.gold ? "text-gb-gold" : "font-semibold"}>
                          {r.value}
                        </span>
                      </div>
                    ))}
                  </div>
                  <MiniBarChart />
                </div>
              ))}
            </div>
            <div className="text-center pt-4">
              <Link
                href="/app/glowbot/modeling"
                className="text-gb-gold text-sm inline-flex items-center gap-1 hover:underline"
              >
                View Full Modeling <ArrowUpRightIcon />
              </Link>
            </div>
          </section>
        </>
      )}
    </div>
  );
}
